version: '3'
services:
  cron:
    image: fballiano/magento2-cron
    depends_on:
      - apache
      - varnish
    links:
      - db
      - cache
      - clusterdata
      - apache
      - varnish
    volumes:
      - ./magento2:/var/www/html
      - ./varnish.secret:/varnish.secret
      # Enable the next line if you want to add a custom php.ini
      - ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  ssl:
    image: fballiano/nginx-ssl-for-magento2
    depends_on:
      - varnish
    links:
      - varnish
    volumes:
      - ./fake-certificates/default-fake.crt:/etc/nginx/ssl/default-fake.crt
      - ./fake-certificates/default-fake.key:/etc/nginx/ssl/default-fake.key
      - ./nginx-default.conf:/etc/nginx/conf.d/fballiano-magento2.conf
    ports:
      - "443:443"

  varnish:
    image: fballiano/varnish
    ports:
      - "80:80"
      - "6082:6082"
    depends_on:
      - apache
    links:
      - apache
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
      - ./varnish.secret:/etc/varnish/secret
    environment:
      - CACHE_SIZE=256M

  apache:
    image: fballiano/magento2-apache-php
    depends_on:
      - db
      - cache
      - clusterdata
    links:
      - db
      - cache
      - clusterdata
    volumes:
      - ./magento2:/var/www/html
      - ~/.composer/auth.json:/root/.composer/auth.json
      # Enable the next line if you want to add a custom php.ini
      - ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8081:8081"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"

  cache:
    image: fballiano/redis-volatile

  clusterdata:
    image: fballiano/redis-volatile

volumes:
  dbdata:
